### ISSUE TITLE
Put a posts helper onto feeds that returns a cursor of posts from that feed

### ISSUE THREAD

**Issue by Neobii** [copleykj/socialize-postable#1]

**Comment by copleykj** [comment]
There actually used to be a method for this which I removed because I felt like others might want this to be have in a different way than what I would imagine it to. Maybe they want just posts by the users friends, or users posts + friends posts, or just the users posts.

Recently I did restructure the code to allow the feed to be more extensible by adding methods to it like you can the rest of the models. This will allow the easy addition of the post method in any form one wishes to create it.

**Comment by copleykj** [comment]
I will see if I can push out the code that allows this between getting home and leaving for my shift at my second job. Should be able to get it done after dinner I believe.

**Comment by Neobii** [comment]
Well, I think generating the feed with option could be part of the feeds
usefulness. Here's an example:
Meteor.user.feed({"friends","friends-likes","friends-comments","new-friends"})
could be some options that are passed in to display certain things on the
user feed.
