### ISSUE TITLE
retrieving posts from a feed?

### ISSUE THREAD

**Issue by RamyElkest** [copleykj/socialize-postable#6]
is it just me or there's no way to retrieve the posts from the feed, the api seems weird to me

I was expecting a user.feed().posts() which i guess returns Meteor.posts.find({userId: this.userId})

this might have been changed with the es6 changes mentioned in the other issue. :+1:

**Comment by copleykj** [comment]
It's not just you. I've actually removed the feed part and transitioned this so that you can basically make anything into a feed. So now the user isn't modified in a weird way to return a feed that then has methods on it. Instead you can use the Abstract Class/Mix-in syntax to create a new class that has the same methods that the feed used and it can be used for many different types of things. For example this can now be used to make groups that can be posted in AND also a profile class for user profiles that can be posted to.

Unfortunately the API for this is not quite as simple but currently my plan is to add a groups package and possibly use this in the user-profile package as well.

**Comment by copleykj** [comment]
I decided to bring back this functionality, and it's available as a new repo at https://github.com/copleykj/socialize-feed. Once I'm done with all the package updates I'll release the new package on atmosphere.
